name: weight_tracker
description: "Track weight in a Flutter app with a Firestore back-end."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # General
  provider: 6.1.1
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  go_router: 12.1.1
  flutter_hooks: 0.20.3

  # Cloud
  firebase_core: 2.24.0
  firebase_auth: 4.15.0
  cloud_firestore: 4.13.3

  # Code generators
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1

  # Code generators
  build_runner: 2.4.7
  json_serializable: 6.7.1
  freezed: 2.4.5

flutter:
  uses-material-design: true
